- name: try installing basic ansible pacman packages
  pacman:
    name: "{{ ansible_pacman_packages}}"
    state: latest
  register: basepacmanpkg

- name: bootstrap archieboi when above fails
  raw: pacman -S python
  when: basepacmanpkg is failed

- name: good curve
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ good_packages }}"

- name: better bow
  package:
    name: "{{ item }}"
    state: absent
  with_items:
    - "{{ bad_packages }}"

...
