---

- name: if intel then set grubby boi
  copy:
    src: files/grub-intel
    dest: /etc/default/grub
    owner: root
    group: root
    mode: 0644
    backup: yes
    force: yes
  when: ansible_processor[1] == "GenuineIntel" or ansible_processor[0] == "GenuineIntel"

- name: if amd then set grubby boi
  copy:
    src: files/grub-amd
    dest: /etc/default/grub
    owner: root
    group: root
    mode: 0644
    backup: yes
    force: yes
  when: ansible_processor[1] == "AuthenticAMD" or ansible_processor[0] == "AuthenticAMD"

- name: regenerate grub.cfg
  command: 'update-grub'

...
